package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.util.Utility;

public final class imagepasswordset3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 8 ]><html class=\"ie ie8\" class=\"no-js\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if (gte IE 9)|!(IE)]><!--><html class=\"no-js\" lang=\"en\"> <!--<![endif]-->\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>Graphical_Authentication_System</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS FILES -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" media=\"screen\" data-name=\"skins\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/layout/wide.css\" data-name=\"layout\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/switcher.css\" media=\"screen\" />\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"Style/css/vendor/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"Style/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"Style/css/style.css\" media=\"screen\" data-name=\"skins\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Style/css/style-fraction.css\" type=\"text/css\" charset=\"utf-8\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Style/css/fractionslider.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"Style/css/switcher.css\" media=\"screen\" />\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    td{\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("        background: -moz-linear-gradient(top, #ffffff, #D1E3E9);\r\n");
      out.write("        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#ffffff), to(#D1E3E9));\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        width: 50px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    td img {\r\n");
      out.write("    max-width:100%;\r\n");
      out.write("    height:auto;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("    td:hover{\r\n");
      out.write("        background: -moz-linear-gradient(top, #249ee4, #057cc0);\r\n");
      out.write("        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#249ee4), to(#057cc0));\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    td:active\r\n");
      out.write("    {\r\n");
      out.write("        background: -moz-linear-gradient(top, #057cc0, #249ee4);\r\n");
      out.write("        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#057cc0), to(#249ee4));\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    #result{\r\n");
      out.write("        font-weight:bold;\r\n");
      out.write("        font-size:16pt;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #myTable{\r\n");
      out.write("        width:300px; height:400px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script  src=\"js/jquery-1.9.1.min.js\" ></script>      \r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\"#myTable td\").click(function() {     \r\n");
      out.write(" \r\n");
      out.write("            var column_num = parseInt( $(this).index() ) + 1;\r\n");
      out.write("            var row_num = parseInt( $(this).parent().index() )+1;    \r\n");
      out.write("            window.location.href = \"imagepasswordset3.jsp?no=\"+2+\"&x=\"+column_num+\"&y=\"+row_num;\r\n");
      out.write("            /* $(\"#result\").html( \"Row_num =\" + row_num + \"  ,  Rolumn_num =\"+ column_num );  */  \r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/tablecss/CSS/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script class=\"jsbin\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String image=session.getAttribute("randomimage3").toString();
System.out.println("------randimg3---"+image);

      out.write("\r\n");
      out.write("<!--Start Header-->\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("    <div id=\"top-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-8 top-info hidden-xs\">\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"logo-bar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- Logo / Mobile Menu -->\r\n");
      out.write("                <div  class=\"col-lg-3 col-sm-3 \">\r\n");
      out.write("                    <div id=\"logo\">\r\n");
      out.write("                         <h1><a href=\"index.jsp\"><img alt=\"logo\" style=\"width: 1200px; height: 100px\" src=\"images/title.png\"/></a></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Navigation\r\n");
      out.write("================================================== -->\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--End Header-->\r\n");
      out.write("\r\n");
      out.write("<!--start wrapper-->\r\n");
      out.write("<section class=\"wrapper\">\r\n");
      out.write("    <section class=\"page_head\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-sm-12\">\r\n");
      out.write("                    <div class=\"page_title\">\r\n");
      out.write("                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row sub_content\">\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            <div class=\"col-lg-6 col-sm-6\" style=\"position:absolute; top: 250px;left: 400px;height:200px;\">\r\n");
      out.write("                <div class=\"dividerHeading\">\r\n");
      out.write("                    <h4><span>Image Password Setting</span></h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <table id=\"myTable\" border=\"1\" style=\"border-collapse: collapse;\"  >\r\n");
      out.write("        <!--1st ROW-->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td ><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img0.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img1.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img2.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img3.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img4.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img5.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \r\n");
      out.write("        <!--2nd ROW-->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img6.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img7.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img8.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img9.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img10.jpg\"></td>\r\n");
      out.write("              <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img11.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \r\n");
      out.write("        <!--3rd ROW-->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img12.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img13.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img14.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img15.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img16.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img17.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \r\n");
      out.write("        <!--4th ROW-->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img18.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img19.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img20.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img21.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img22.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img23.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write(" \r\n");
      out.write("        <!--5th ROW-->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img24.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img25.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img26.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img27.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img28.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img29.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img30.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img31.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img32.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img33.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img34.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img35.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img36.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img37.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img38.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img39.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img40.jpg\"></td>\r\n");
      out.write("             <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img41.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img42.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img43.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img44.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img45.jpg\"></td>\r\n");
      out.write("            <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img46.jpg\"></td>\r\n");
      out.write("             <td><img src=\"");
      out.print(request.getContextPath());
      out.write("/PasswordImages/");
      out.print(image);
      out.write("/Imageblocks/img47.jpg\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("                \r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"col-lg-6 col-sm-6\"  style=\"position:absolute; top: 300px;left: 850px; width:300px;\">\r\n");
      out.write("              \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("       ");


	if(Utility.parse(request.getParameter("no"))==2)
    {
    
    String column=request.getParameter("x");
    String row=request.getParameter("y");
    
    
    System.out.println("====column==="+column);
    System.out.println("====row==="+row);
    
      out.write("         \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <form id=\"registerform\" method=\"get\" name=\"registerform\" action=\"");
      out.print(request.getContextPath());
      out.write("/Recievescriptdata\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        Column:<input type=\"text\" class=\"form-control\" name=\"column\" value=\"");
      out.print(column);
      out.write("\">\r\n");
      out.write("                        Row:<input type=\"text\"  class=\"form-control\" name=\"row\" value=\"");
      out.print(row);
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                     <button type=\"submit\" name=\"submit\" value=\"recieve3\" class=\"btn btn-default btn-lg button\">Submit</button>\r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.cookie.js\"></script> <!-- jQuery cookie -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/styleswitch.js\"></script> <!-- Style Colors Switcher -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.smartmenus.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.smartmenus.bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/owl.carousel.js\"></script><!-- Popover-JS -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jflickrfeed.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.isotope.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/swipe.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-scrolltofixed-min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Start Style Switcher -->\r\n");
      out.write("\r\n");
      out.write("<!-- End Style Switcher -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
